### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by csikoszoltan** [Rareloop/lumberjack-bedrock-installer#2]
Hello,
Running `lumberjack-bedrock new my-site` gives the following error:
<img width="1195" alt="Screenshot 2022-04-06 at 20 49 57" src="https://user-images.githubusercontent.com/44744239/162047680-6c6c94ea-bbc0-4565-9e6e-dd80e9366712.png">

Composer 2.3.3
PHP 8.0

Is there any fix for this?

Thanks!

**Comment by arnaudbagnis** [comment]
i have same error

**Comment by adamtomat** [comment]
Looks like you are running PHP 8.0, which was previously unsupported. However earlier today we added PHP 8.0 support so this specific issue should now be resolved 👍 

However, we are also aware of another issue that we are waiting for Timber to resolve - and until then the installer won't work fully. This is the MR in question. They have merged it, but we are waiting for them to tag it before it fixes our installer:

https://github.com/timber/timber/pull/2550
